name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  test:
    name: Tests on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
      - uses: Hanaasagi/zig-action-cache@v1.1.1
        with:
          cache-on-failure: true
      - run: zig version
      - run: zig env
      - run: ls
      - run: ls zig-cache || echo 'no zig-cache'
      - name: Build
        run: zig build --verbose
      - name: Run Tests
        run: zig build test
